export const colors = [
  'baby-blue',
  'blue-green',
  'blue-grotto',
  'navy-blue',
  'pewter',
  'brose-red',
  'terra-cotta',
  'gunmetal',
  'metalic-silver',
  'soap-stone',
  'mid-grey',
  'regent-grey',
  'seas-hell',
  'antique-white',
  'white',
];
